<?php


if ( ! isset( $content_width ) ) $content_width = 960;


function wpeden_meta_box_icons(){
    global $post;


    $tnicons = "tn-arrow-up
tn-arrow-right
tn-arrow-left
tn-arrow-down
tn-arrows-vertical
tn-arrows-horizontal
tn-angle-up
tn-angle-right
tn-angle-left
tn-angle-down
tn-angle-double-up
tn-angle-double-right
tn-angle-double-left
tn-angle-double-down
tn-move
tn-fullscreen
tn-arrow-top-right
tn-arrow-top-left
tn-arrow-circle-up
tn-arrow-circle-right
tn-arrow-circle-left
tn-arrow-circle-down
tn-arrows-corner
tn-split-v
tn-split-v-alt
tn-split-h
tn-hand-point-up
tn-hand-point-right
tn-hand-point-left
tn-hand-point-down
tn-back-right
tn-back-left
tn-exchange-vertical
tn-wand
tn-save
tn-save-alt
tn-direction
tn-direction-alt
tn-user
tn-link
tn-unlink
tn-trash
tn-target
tn-tag
tn-desktop
tn-tablet
tn-mobile
tn-email
tn-star
tn-spray
tn-signal
tn-shopping-cart
tn-shopping-cart-full
tn-settings
tn-search
tn-zoom-in
tn-zoom-out
tn-cut
tn-ruler
tn-ruler-alt-2
tn-ruler-pencil
tn-ruler-alt
tn-bookmark
tn-bookmark-alt
tn-reload
tn-plus
tn-minus
tn-close
tn-pin
tn-pencil
tn-pencil-alt
tn-paint-roller
tn-paint-bucket
tn-na
tn-medall
tn-medall-alt
tn-marker
tn-marker-alt
tn-lock
tn-unlock
tn-location-arrow
tn-layout
tn-layers
tn-layers-alt
tn-key
tn-image
tn-heart
tn-heart-broken
tn-hand-stop
tn-hand-open
tn-hand-drag
tn-flag
tn-flag-alt
tn-flag-alt-2
tn-eye
tn-import
tn-export
tn-cup
tn-crown
tn-comments
tn-comment
tn-comment-alt
tn-thought
tn-clip
tn-check
tn-check-box
tn-camera
tn-announcement
tn-brush
tn-brush-alt
tn-palette
tn-briefcase
tn-bolt
tn-bolt-alt
tn-blackboard
tn-bag
tn-world
tn-wheelchair
tn-car
tn-truck
tn-timer
tn-ticket
tn-thumb-up
tn-thumb-down
tn-stats-up
tn-stats-down
tn-shine
tn-shift-right
tn-shift-left
tn-shift-right-alt
tn-shift-left-alt
tn-shield
tn-notepad
tn-server
tn-pulse
tn-printer
tn-power-off
tn-plug
tn-pie-chart
tn-panel
tn-package
tn-music
tn-music-alt
tn-mouse
tn-mouse-alt
tn-money
tn-microphone
tn-menu
tn-menu-alt
tn-map
tn-map-alt
tn-location-pin
tn-light-bulb
tn-info
tn-infinite
tn-id-badge
tn-hummer
tn-home
tn-help
tn-headphone
tn-harddrives
tn-harddrive
tn-gift
tn-game
tn-filter
tn-files
tn-file
tn-zip
tn-folder
tn-envelope
tn-dashboard
tn-cloud
tn-cloud-up
tn-cloud-down
tn-clipboard
tn-calendar
tn-book
tn-bell
tn-basketball
tn-bar-chart
tn-bar-chart-alt
tn-archive
tn-anchor
tn-alert
tn-alarm-clock
tn-agenda
tn-write
tn-wallet
tn-video-clapper
tn-video-camera
tn-vector
tn-support
tn-stamp
tn-slice
tn-shortcode
tn-receipt
tn-pin2
tn-pin-alt
tn-pencil-alt2
tn-eraser
tn-more
tn-more-alt
tn-microphone-alt
tn-magnet
tn-line-double
tn-line-dotted
tn-line-dashed
tn-ink-pen
tn-info-alt
tn-help-alt
tn-headphone-alt
tn-gallery
tn-face-smile
tn-face-sad
tn-credit-card
tn-comments-smiley
tn-time
tn-share
tn-share-alt
tn-rocket
tn-new-window
tn-rss
tn-rss-alt
tn-control-stop
tn-control-shuffle
tn-control-play
tn-control-pause
tn-control-forward
tn-control-backward
tn-volume
tn-control-skip-forward
tn-control-skip-backward
tn-control-record
tn-control-eject
tn-paragraph
tn-uppercase
tn-underline
tn-text
tn-Italic
tn-smallcap
tn-list
tn-list-ol
tn-align-right
tn-align-left
tn-align-justify
tn-align-center
tn-quote-right
tn-quote-left
tn-layout-width-full
tn-layout-width-default
tn-layout-width-default-alt
tn-layout-tab
tn-layout-tab-window
tn-layout-tab-v
tn-layout-tab-min
tn-layout-slider
tn-layout-slider-alt
tn-layout-sidebar-right
tn-layout-sidebar-none
tn-layout-sidebar-left
tn-layout-placeholder
tn-layout-menu
tn-layout-menu-v
tn-layout-menu-separated
tn-layout-menu-full
tn-layout-media-right
tn-layout-media-right-alt
tn-layout-media-overlay
tn-layout-media-overlay-alt
tn-layout-media-overlay-alt-2
tn-layout-media-left
tn-layout-media-left-alt
tn-layout-media-center
tn-layout-media-center-alt
tn-layout-list-thumb
tn-layout-list-thumb-alt
tn-layout-list-post
tn-layout-list-large-image
tn-layout-line-solid
tn-layout-grid4
tn-layout-grid3
tn-layout-grid2
tn-layout-grid2-thumb
tn-layout-cta-right
tn-layout-cta-left
tn-layout-cta-center
tn-layout-cta-btn-right
tn-layout-cta-btn-left
tn-layout-column4
tn-layout-column3
tn-layout-column2
tn-layout-accordion-separated
tn-layout-accordion-merged
tn-layout-accordion-list
tn-widgetized
tn-widget
tn-widget-alt
tn-view-list
tn-view-list-alt
tn-view-grid
tn-upload
tn-download
tn-loop
tn-layout-sidebar-2
tn-layout-grid4-alt
tn-layout-grid3-alt
tn-layout-grid2-alt
tn-layout-column4-alt
tn-layout-column3-alt
tn-layout-column2-alt
tn-flickr
tn-flickr-alt
tn-instagram
tn-google
tn-github
tn-facebook
tn-dropbox
tn-dropbox-alt
tn-dribbble
tn-apple
tn-android
tn-yahoo
tn-trello
tn-stack-overflow
tn-soundcloud
tn-sharethis
tn-sharethis-alt
tn-reddit
tn-microsoft
tn-microsoft-alt
tn-linux
tn-jsfiddle
tn-joomla
tn-html5
tn-css3
tn-drupal
tn-wordpress
tn-tumblr
tn-tumblr-alt
tn-skype
tn-youtube
tn-vimeo
tn-vimeo-alt
tn-twitter
tn-twitter-alt
tn-linkedin
tn-pinterest
tn-pinterest-alt
tn-themify-logo
tn-themify-favicon
tn-themify-favicon-alt";

    $icons = explode("\n", $tnicons);

    $data = maybe_unserialize(get_post_meta($post->ID,'wpeden_post_meta', true));
    if(is_array($data)) {
        $icon = sanitize_text_field( $data['icon'] );
    }
    ?>
    <style>
        .dicon{
            float: left;
            width: 16px;
            height: 16px;
            text-align: center;
            line-height: 16px;
            font-size: 14px;
            padding: 5px;
            margin:5px;
            display: block;
            border: 1px solid #dddddd;
            border-radius: 2px;
            transition: all 0.3s ease-in-out;
        }
        .dicon:hover{
            border: 1px solid #1E8CBE;
            transition: all 0.3s ease-in-out;
        }
        .dicon.active{
            border: 1px solid #1E8CBE;
            background: #1E8CBE;
            color: #ffffff;
            transition: all 0.3s ease-in-out;
        }
    </style>
    <script>
        jQuery(function($){
            $('.dicon').click(function(){
                $('.dicon').removeClass('active');
                $(this).addClass('active');
            });
        });
    </script>
    <div style="max-height: 200px;overflow: auto">
        <link href="<?php echo get_template_directory_uri().'/fonts/icons/icons.css'; ?>" rel="stylesheet" type="text/css" />
        <?php

        echo "<label class='dicon active' title='{$icon}'><input style='display:none;' type=radio name='wpeden_post_meta[icon]' value='{$icon}' checked=checked ><i class='{$icon}'></i></label>";
        foreach($icons  as $class ){ if($class != $icon) echo "<label title='{$class}' class='dicon ".($class == $icon?'active':'')."'><input style='display:none;' type=radio name='wpeden_post_meta[icon]' value='{$class}' ".checked($class, $icon, false)."><i class='{$class}'></i></label>"; } ?>
        <div style="clear: both;"></div>
    </div>
<?php

}


function wpeden_all_icons(){

    $faicons = "fa-angellist
fa-area-chart
fa-at
fa-bell-slash
fa-bell-slash-o
fa-bicycle
fa-binoculars
fa-birthday-cake
fa-bus
fa-calculator
fa-cc
fa-cc-amex
fa-cc-discover
fa-cc-mastercard
fa-cc-paypal
fa-cc-stripe
fa-cc-visa
fa-copyright
fa-eyedropper
fa-futbol-o
fa-google-wallet
fa-ils
fa-ioxhost
fa-lastfm
fa-lastfm-square
fa-line-chart
fa-meanpath
fa-newspaper-o
fa-paint-brush
fa-paypal
fa-pie-chart
fa-plug
fa-shekel
fa-sheqel
fa-slideshare
fa-soccer-ball-o
fa-toggle-off
fa-toggle-on
fa-trash
fa-tty
fa-twitch
fa-wifi
fa-yelp
fa-adjust
fa-anchor
fa-archive
fa-area-chart
fa-arrows
fa-arrows-h
fa-arrows-v
fa-asterisk
fa-at
fa-automobile
fa-ban
fa-bank
fa-bar-chart
fa-bar-chart-o
fa-barcode
fa-bars
fa-beer
fa-bell
fa-bell-o
fa-bell-slash
fa-bell-slash-o
fa-bicycle
fa-binoculars
fa-birthday-cake
fa-bolt
fa-bomb
fa-book
fa-bookmark
fa-bookmark-o
fa-briefcase
fa-bug
fa-building
fa-building-o
fa-bullhorn
fa-bullseye
fa-bus
fa-cab
fa-calculator
fa-calendar
fa-calendar-o
fa-camera
fa-camera-retro
fa-car
fa-caret-square-o-down
fa-caret-square-o-left
fa-caret-square-o-right
fa-caret-square-o-up
fa-cc
fa-certificate
fa-check
fa-check-circle
fa-check-circle-o
fa-check-square
fa-check-square-o
fa-child
fa-circle
fa-circle-o
fa-circle-o-notch
fa-circle-thin
fa-clock-o
fa-close
fa-cloud
fa-cloud-download
fa-cloud-upload
fa-code
fa-code-fork
fa-coffee
fa-cog
fa-cogs
fa-comment
fa-comment-o
fa-comments
fa-comments-o
fa-compass
fa-copyright
fa-credit-card
fa-crop
fa-crosshairs
fa-cube
fa-cubes
fa-cutlery
fa-dashboard
fa-database
fa-desktop
fa-dot-circle-o
fa-download
fa-edit
fa-ellipsis-h
fa-ellipsis-v
fa-envelope
fa-envelope-o
fa-envelope-square
fa-eraser
fa-exchange
fa-exclamation
fa-exclamation-circle
fa-exclamation-triangle
fa-external-link
fa-external-link-square
fa-eye
fa-eye-slash
fa-eyedropper
fa-fax
fa-female
fa-fighter-jet
fa-file-archive-o
fa-file-audio-o
fa-file-code-o
fa-file-excel-o
fa-file-image-o
fa-file-movie-o
fa-file-pdf-o
fa-file-photo-o
fa-file-picture-o
fa-file-powerpoint-o
fa-file-sound-o
fa-file-video-o
fa-file-word-o
fa-file-zip-o
fa-film
fa-filter
fa-fire
fa-fire-extinguisher
fa-flag
fa-flag-checkered
fa-flag-o
fa-flash
fa-flask
fa-folder
fa-folder-o
fa-folder-open
fa-folder-open-o
fa-frown-o
fa-futbol-o
fa-gamepad
fa-gavel
fa-gear
fa-gears
fa-gift
fa-glass
fa-globe
fa-graduation-cap
fa-group
fa-hdd-o
fa-headphones
fa-heart
fa-heart-o
fa-history
fa-home
fa-image
fa-inbox
fa-info
fa-info-circle
fa-institution
fa-key
fa-keyboard-o
fa-language
fa-laptop
fa-leaf
fa-legal
fa-lemon-o
fa-level-down
fa-level-up
fa-life-bouy
fa-life-buoy
fa-life-ring
fa-life-saver
fa-lightbulb-o
fa-line-chart
fa-location-arrow
fa-lock
fa-magic
fa-magnet
fa-mail-forward
fa-mail-reply
fa-mail-reply-all
fa-male
fa-map-marker
fa-meh-o
fa-microphone
fa-microphone-slash
fa-minus
fa-minus-circle
fa-minus-square
fa-minus-square-o
fa-mobile
fa-mobile-phone
fa-money
fa-moon-o
fa-mortar-board
fa-music
fa-navicon
fa-newspaper-o
fa-paint-brush
fa-paper-plane
fa-paper-plane-o
fa-paw
fa-pencil
fa-pencil-square
fa-pencil-square-o
fa-phone
fa-phone-square
fa-photo
fa-picture-o
fa-pie-chart
fa-plane
fa-plug
fa-plus
fa-plus-circle
fa-plus-square
fa-plus-square-o
fa-power-off
fa-print
fa-puzzle-piece
fa-qrcode
fa-question
fa-question-circle
fa-quote-left
fa-quote-right
fa-random
fa-recycle
fa-refresh
fa-remove
fa-reorder
fa-reply
fa-reply-all
fa-retweet
fa-road
fa-rocket
fa-rss
fa-rss-square
fa-search
fa-search-minus
fa-search-plus
fa-send
fa-send-o
fa-share
fa-share-alt
fa-share-alt-square
fa-share-square
fa-share-square-o
fa-shield
fa-shopping-cart
fa-sign-in
fa-sign-out
fa-signal
fa-sitemap
fa-sliders
fa-smile-o
fa-soccer-ball-o
fa-sort
fa-sort-alpha-asc
fa-sort-alpha-desc
fa-sort-amount-asc
fa-sort-amount-desc
fa-sort-asc
fa-sort-desc
fa-sort-down
fa-sort-numeric-asc
fa-sort-numeric-desc
fa-sort-up
fa-space-shuttle
fa-spinner
fa-spoon
fa-square
fa-square-o
fa-star
fa-star-half
fa-star-half-empty
fa-star-half-full
fa-star-half-o
fa-star-o
fa-suitcase
fa-sun-o
fa-support
fa-tablet
fa-tachometer
fa-tag
fa-tags
fa-tasks
fa-taxi
fa-terminal
fa-thumb-tack
fa-thumbs-down
fa-thumbs-o-down
fa-thumbs-o-up
fa-thumbs-up
fa-ticket
fa-times
fa-times-circle
fa-times-circle-o
fa-tint
fa-toggle-down
fa-toggle-left
fa-toggle-off
fa-toggle-on
fa-toggle-right
fa-toggle-up
fa-trash
fa-trash-o
fa-tree
fa-trophy
fa-truck
fa-tty
fa-umbrella
fa-university
fa-unlock
fa-unlock-alt
fa-unsorted
fa-upload
fa-user
fa-users
fa-video-camera
fa-volume-down
fa-volume-off
fa-volume-up
fa-warning
fa-wheelchair
fa-wifi
fa-wrench
fa-file
fa-file-archive-o
fa-file-audio-o
fa-file-code-o
fa-file-excel-o
fa-file-image-o
fa-file-movie-o
fa-file-o
fa-file-pdf-o
fa-file-photo-o
fa-file-picture-o
fa-file-powerpoint-o
fa-file-sound-o
fa-file-text
fa-file-text-o
fa-file-video-o
fa-file-word-o
fa-file-zip-o
fa-circle-o-notch
fa-cog
fa-gear
fa-refresh
fa-spinner
fa-check-square
fa-check-square-o
fa-circle
fa-circle-o
fa-dot-circle-o
fa-minus-square
fa-minus-square-o
fa-plus-square
fa-plus-square-o
fa-square
fa-square-o
fa-cc-amex
fa-cc-discover
fa-cc-mastercard
fa-cc-paypal
fa-cc-stripe
fa-cc-visa
fa-credit-card
fa-google-wallet
fa-paypal
fa-area-chart
fa-bar-chart
fa-bar-chart-o
fa-line-chart
fa-pie-chart
fa-bitcoin
fa-btc
fa-cny
fa-dollar
fa-eur
fa-euro
fa-gbp
fa-ils
fa-inr
fa-jpy
fa-krw
fa-money
fa-rmb
fa-rouble
fa-rub
fa-ruble
fa-rupee
fa-shekel
fa-sheqel
fa-try
fa-turkish-lira
fa-usd
fa-won
fa-yen
fa-align-center
fa-align-justify
fa-align-left
fa-align-right
fa-bold
fa-chain
fa-chain-broken
fa-clipboard
fa-columns
fa-copy
fa-cut
fa-dedent
fa-eraser
fa-file
fa-file-o
fa-file-text
fa-file-text-o
fa-files-o
fa-floppy-o
fa-font
fa-header
fa-indent
fa-italic
fa-link
fa-list
fa-list-alt
fa-list-ol
fa-list-ul
fa-outdent
fa-paperclip
fa-paragraph
fa-paste
fa-repeat
fa-rotate-left
fa-rotate-right
fa-save
fa-scissors
fa-strikethrough
fa-subscript
fa-superscript
fa-table
fa-text-height
fa-text-width
fa-th
fa-th-large
fa-th-list
fa-underline
fa-undo
fa-unlink
fa-angle-double-down
fa-angle-double-left
fa-angle-double-right
fa-angle-double-up
fa-angle-down
fa-angle-left
fa-angle-right
fa-angle-up
fa-arrow-circle-down
fa-arrow-circle-left
fa-arrow-circle-o-down
fa-arrow-circle-o-left
fa-arrow-circle-o-right
fa-arrow-circle-o-up
fa-arrow-circle-right
fa-arrow-circle-up
fa-arrow-down
fa-arrow-left
fa-arrow-right
fa-arrow-up
fa-arrows
fa-arrows-alt
fa-arrows-h
fa-arrows-v
fa-caret-down
fa-caret-left
fa-caret-right
fa-caret-square-o-down
fa-caret-square-o-left
fa-caret-square-o-right
fa-caret-square-o-up
fa-caret-up
fa-chevron-circle-down
fa-chevron-circle-left
fa-chevron-circle-right
fa-chevron-circle-up
fa-chevron-down
fa-chevron-left
fa-chevron-right
fa-chevron-up
fa-hand-o-down
fa-hand-o-left
fa-hand-o-right
fa-hand-o-up
fa-long-arrow-down
fa-long-arrow-left
fa-long-arrow-right
fa-long-arrow-up
fa-toggle-down
fa-toggle-left
fa-toggle-right
fa-toggle-up
fa-arrows-alt
fa-backward
fa-compress
fa-eject
fa-expand
fa-fast-backward
fa-fast-forward
fa-forward
fa-pause
fa-play
fa-play-circle
fa-play-circle-o
fa-step-backward
fa-step-forward
fa-stop
fa-youtube-play
";
    $tnicons = "tn-arrow-up
tn-arrow-right
tn-arrow-left
tn-arrow-down
tn-arrows-vertical
tn-arrows-horizontal
tn-angle-up
tn-angle-right
tn-angle-left
tn-angle-down
tn-angle-double-up
tn-angle-double-right
tn-angle-double-left
tn-angle-double-down
tn-move
tn-fullscreen
tn-arrow-top-right
tn-arrow-top-left
tn-arrow-circle-up
tn-arrow-circle-right
tn-arrow-circle-left
tn-arrow-circle-down
tn-arrows-corner
tn-split-v
tn-split-v-alt
tn-split-h
tn-hand-point-up
tn-hand-point-right
tn-hand-point-left
tn-hand-point-down
tn-back-right
tn-back-left
tn-exchange-vertical
tn-wand
tn-save
tn-save-alt
tn-direction
tn-direction-alt
tn-user
tn-link
tn-unlink
tn-trash
tn-target
tn-tag
tn-desktop
tn-tablet
tn-mobile
tn-email
tn-star
tn-spray
tn-signal
tn-shopping-cart
tn-shopping-cart-full
tn-settings
tn-search
tn-zoom-in
tn-zoom-out
tn-cut
tn-ruler
tn-ruler-alt-2
tn-ruler-pencil
tn-ruler-alt
tn-bookmark
tn-bookmark-alt
tn-reload
tn-plus
tn-minus
tn-close
tn-pin
tn-pencil
tn-pencil-alt
tn-paint-roller
tn-paint-bucket
tn-na
tn-medall
tn-medall-alt
tn-marker
tn-marker-alt
tn-lock
tn-unlock
tn-location-arrow
tn-layout
tn-layers
tn-layers-alt
tn-key
tn-image
tn-heart
tn-heart-broken
tn-hand-stop
tn-hand-open
tn-hand-drag
tn-flag
tn-flag-alt
tn-flag-alt-2
tn-eye
tn-import
tn-export
tn-cup
tn-crown
tn-comments
tn-comment
tn-comment-alt
tn-thought
tn-clip
tn-check
tn-check-box
tn-camera
tn-announcement
tn-brush
tn-brush-alt
tn-palette
tn-briefcase
tn-bolt
tn-bolt-alt
tn-blackboard
tn-bag
tn-world
tn-wheelchair
tn-car
tn-truck
tn-timer
tn-ticket
tn-thumb-up
tn-thumb-down
tn-stats-up
tn-stats-down
tn-shine
tn-shift-right
tn-shift-left
tn-shift-right-alt
tn-shift-left-alt
tn-shield
tn-notepad
tn-server
tn-pulse
tn-printer
tn-power-off
tn-plug
tn-pie-chart
tn-panel
tn-package
tn-music
tn-music-alt
tn-mouse
tn-mouse-alt
tn-money
tn-microphone
tn-menu
tn-menu-alt
tn-map
tn-map-alt
tn-location-pin
tn-light-bulb
tn-info
tn-infinite
tn-id-badge
tn-hummer
tn-home
tn-help
tn-headphone
tn-harddrives
tn-harddrive
tn-gift
tn-game
tn-filter
tn-files
tn-file
tn-zip
tn-folder
tn-envelope
tn-dashboard
tn-cloud
tn-cloud-up
tn-cloud-down
tn-clipboard
tn-calendar
tn-book
tn-bell
tn-basketball
tn-bar-chart
tn-bar-chart-alt
tn-archive
tn-anchor
tn-alert
tn-alarm-clock
tn-agenda
tn-write
tn-wallet
tn-video-clapper
tn-video-camera
tn-vector
tn-support
tn-stamp
tn-slice
tn-shortcode
tn-receipt
tn-pin2
tn-pin-alt
tn-pencil-alt2
tn-eraser
tn-more
tn-more-alt
tn-microphone-alt
tn-magnet
tn-line-double
tn-line-dotted
tn-line-dashed
tn-ink-pen
tn-info-alt
tn-help-alt
tn-headphone-alt
tn-gallery
tn-face-smile
tn-face-sad
tn-credit-card
tn-comments-smiley
tn-time
tn-share
tn-share-alt
tn-rocket
tn-new-window
tn-rss
tn-rss-alt
tn-control-stop
tn-control-shuffle
tn-control-play
tn-control-pause
tn-control-forward
tn-control-backward
tn-volume
tn-control-skip-forward
tn-control-skip-backward
tn-control-record
tn-control-eject
tn-paragraph
tn-uppercase
tn-underline
tn-text
tn-Italic
tn-smallcap
tn-list
tn-list-ol
tn-align-right
tn-align-left
tn-align-justify
tn-align-center
tn-quote-right
tn-quote-left
tn-layout-width-full
tn-layout-width-default
tn-layout-width-default-alt
tn-layout-tab
tn-layout-tab-window
tn-layout-tab-v
tn-layout-tab-min
tn-layout-slider
tn-layout-slider-alt
tn-layout-sidebar-right
tn-layout-sidebar-none
tn-layout-sidebar-left
tn-layout-placeholder
tn-layout-menu
tn-layout-menu-v
tn-layout-menu-separated
tn-layout-menu-full
tn-layout-media-right
tn-layout-media-right-alt
tn-layout-media-overlay
tn-layout-media-overlay-alt
tn-layout-media-overlay-alt-2
tn-layout-media-left
tn-layout-media-left-alt
tn-layout-media-center
tn-layout-media-center-alt
tn-layout-list-thumb
tn-layout-list-thumb-alt
tn-layout-list-post
tn-layout-list-large-image
tn-layout-line-solid
tn-layout-grid4
tn-layout-grid3
tn-layout-grid2
tn-layout-grid2-thumb
tn-layout-cta-right
tn-layout-cta-left
tn-layout-cta-center
tn-layout-cta-btn-right
tn-layout-cta-btn-left
tn-layout-column4
tn-layout-column3
tn-layout-column2
tn-layout-accordion-separated
tn-layout-accordion-merged
tn-layout-accordion-list
tn-widgetized
tn-widget
tn-widget-alt
tn-view-list
tn-view-list-alt
tn-view-grid
tn-upload
tn-download
tn-loop
tn-layout-sidebar-2
tn-layout-grid4-alt
tn-layout-grid3-alt
tn-layout-grid2-alt
tn-layout-column4-alt
tn-layout-column3-alt
tn-layout-column2-alt
tn-flickr
tn-flickr-alt
tn-instagram
tn-google
tn-github
tn-facebook
tn-dropbox
tn-dropbox-alt
tn-dribbble
tn-apple
tn-android
tn-yahoo
tn-trello
tn-stack-overflow
tn-soundcloud
tn-sharethis
tn-sharethis-alt
tn-reddit
tn-microsoft
tn-microsoft-alt
tn-linux
tn-jsfiddle
tn-joomla
tn-html5
tn-css3
tn-drupal
tn-wordpress
tn-tumblr
tn-tumblr-alt
tn-skype
tn-youtube
tn-vimeo
tn-vimeo-alt
tn-twitter
tn-twitter-alt
tn-linkedin
tn-pinterest
tn-pinterest-alt
tn-themify-logo
tn-themify-favicon
tn-themify-favicon-alt";

//    $faicons = explode("\n", $faicons);
//    foreach($faicons as $fa){
//        $name = ucwords(trim(str_replace(array("\r",'tn-','-'),array("","",' '),$fa)));
//        $fa = trim($fa);
//        if($fa!="")
//            $icons["fa $fa"] = "FA: ".$name;
//    }
    $tnicons = explode("\n", $tnicons);
    foreach($tnicons as $tn){
        $name = ucwords(trim(str_replace(array("\r",'tn-','-'),array("","",' '),$tn)));
        $tn = trim($tn);
        if($tn!="")
            $icons[$tn] = "TN: ".$name;
    }

    return $icons;
}

